export interface ContactInfo {
  firstName: string;
  lastName: string;
  email: string;
  company: string;
}

export interface FormState {
  businessType: string;
  needs: string[];
  revenue: string;
  timeline: string;
  budget: string;
  contact: ContactInfo;
}

export interface FormOption {
  label: string;
  value: string;
  icon: string;
  description?: string;
}

export interface FormStep {
  key: string;
  type: 'single' | 'multi' | 'contact';
  title: string;
  subtitle: string;
  options?: FormOption[];
}

/**
 * Interface representing an artifact generated by the model.
 * Used in ArtifactCard.tsx
 */
export interface Artifact {
  id: string;
  html: string;
  status: 'streaming' | 'complete' | string;
  styleName: string;
}